version: '3.9'

services:
  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: be
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - shared-net
    ports:
      - '8080:8080'  
      - '8000:8000'  

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    volumes:
      - ./fe:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      API_URL: http://host.docker.internal:8000
    networks:
      - shared-net



networks:
  shared-net:
    driver: bridge