import Head from "next/head";
import styles from "@/styles/Home.module.css";
import useSocket from "@/hooks/useSocket";
import { useEffect, useRef, useState } from "react";
import VideoComponent from "@/components/VideoComponent";
import { usePlayer } from "@/hooks/usePlayer";

export default function Home() {
  const { socket, on, emit } = useSocket("http://localhost:8000");

  const inputRef = useRef();
  const [videoUrl, setVideoUrl] = useState(
    "https://www.youtube.com/watch?v=r4Pq5lygij8"
  );

  const onPlayerStateChange = (playerState) => {
    emit("playerStateChange", playerState);
    console.log(playerState);
  };

  const onSoundLevelChange = (newVolume) => {
    console.log(newVolume);
    emit("soundChange", { soundLevel: newVolume });
  };

  const onPlaybackRateChange = (playbackRate) => {
    console.log(`playbackRate changed: ${playbackRate}`);
    emit("playbackRateChange", { soundLevel: newVolume });
  };

  const onReady = (event) => {
    event.target.pauseVideo();
  };

  const {
    playerRef,
    seekTo,
    setVolume,
    onStateChange,
    handlePlaybackRateChange,
    play,
    pause,
    playerInfo,
  } = usePlayer(onPlayerStateChange, onSoundLevelChange, onPlaybackRateChange);

  useEffect(() => {
    on("pongg", (data) => {
      console.log("working!", data);
    });

    on("handleSoundChange", (data) => {
      console.log("handleSoundChange!", JSON.parse(data).soundLevel);
      setVolume(JSON.parse(data).soundLevel, true);
    });

    on("handleRateChange", (data) => {
      setRate(data.rate);
    });

    on("handlePlayerStateChange", (data) => {
      console.log("handlePlayerStateChange socket", JSON.parse(data));
      if (JSON.parse(data).playerState == "1") {
        play();
      } else if (JSON.parse(data).playerState == "2") {
        pause();
      }
     seekTo(JSON.parse(data).seekTo);
    });
  }, [on]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button
          onClick={() => {
            emit("pingg");
          }}
        >
          send ping to socket
        </button>

        <VideoComponent
          onStateChange={onStateChange}
          onReady={onReady}
          playerRef={playerRef}
          playerInfo={playerInfo}
          handlePlaybackRateChange={handlePlaybackRateChange}
          url={videoUrl}
        />

        <button
          onClick={() => {
            seekTo(1415.182735);
            setVolume(25);
          }}
        >
          update
        </button>

        <button
          onClick={() => {
            play();
          }}
        >
          play
        </button>

        <button
          onClick={() => {
            pause();
          }}
        >
          pause
        </button>
        <input ref={inputRef} />
        <button onClick={() => setVideoUrl(inputRef.current.value)}>
          Load Video
        </button>
      </main>
    </>
  );
}
