import Head from "next/head";
import styles from "@/styles/Home.module.css";
import useSocket from "@/hooks/useSocket";
import { useEffect, useRef, useState } from "react";
import VideoComponent from "@/components/VideoComponent";
import { usePlayer } from "@/hooks/usePlayer";

export default function Home() {
  const { socket, on, emit } = useSocket("http://localhost:8000");

  const inputRef = useRef();
  const [videoUrl, setVideoUrl] = useState(
    "https://www.youtube.com/watch?v=r4Pq5lygij8"
  );

  const onSoundLevelChange = (newVolume) => {
    console.log(`Volume changed: ${newVolume}`);
  };

  const { playerRef, seekTo, setVolume, onStateChange, playerInfo } =
    usePlayer(onSoundLevelChange);

  const onReady = (event) => {
    event.target.pauseVideo();
  };

  const onPlaybackRateChange = () => {};

  useEffect(() => {
    on("pongg", (data) => {
      console.log("working!", data);
    });
  }, [on]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button
          onClick={() => {
            emit("pingg");
          }}
        >
          send ping to socket
        </button>

        <VideoComponent
          onStateChange={onStateChange}
          onPlaybackRateChange={onPlaybackRateChange}
          onReady={onReady}
          playerRef={playerRef}
          playerInfo={playerInfo}
          url={videoUrl}
        />

        <button
          onClick={() => {
            seekTo(1415.182735);
            setVolume(25);
          }}
        >
          update
        </button>

        <input ref={inputRef} />
        <button onClick={() => setVideoUrl(inputRef.current.value)}>
          Load Video
        </button>
      </main>
    </>
  );
}
