import Head from "next/head";
import styles from "@/styles/Home.module.css";
import useSocket from "@/hooks/useSocket";
import { useEffect, useRef, useState } from "react";
import VideoComponent from "@/components/VideoComponent";

export default function Home() {
  const { socket, on, emit } = useSocket("http://localhost:8000");

  const inputRef = useRef();
  const [videoUrl, setVideoUrl] = useState(
    "https://www.youtube.com/watch?v=r4Pq5lygij8"
  );

  useEffect(() => {
    on("pongg", (data) => {
      console.log("working!", data);
    });
  }, [on]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button
          onClick={() => {
            emit("pingg");
          }}
        >
          send ping to socket
        </button>

        <VideoComponent url={videoUrl} />

        <input ref={inputRef} />
        <button onClick={() => setVideoUrl(inputRef.current.value)}>
          Load Video
        </button>
      </main>
    </>
  );
}
